Repository ELS-RD/transformer-deploy, pull requests merged in 2021-12, with the labels that each got.

#20 Fix install errors
  requirements_gpu.txt
  setup.cfg
Labels: bug, TensorRT

#19 Add auth token
  src/transformer_deploy/convert.py
Labels: Hugging Face

#15 Support GPU INT-8 quantization
  .gitignore
  README.md
  VERSION
  demo/README.md
  demo/quantization_end_to_end.ipynb
  requirements.txt
  requirements_gpu.txt
  src/transformer_deploy/QDQModels/QDQRoberta.py
  src/transformer_deploy/QDQModels/__init__.py
  src/transformer_deploy/backends/ort_utils.py
  src/transformer_deploy/backends/trt_utils.py
  src/transformer_deploy/convert.py
Labels: performance, TensorRT, Hugging Face

#27 refactoring
  .github/workflows/python-app.yml
  Dockerfile
  Makefile
  README.md
  pytest.ini
  requirements.txt
  requirements_cpu.txt
  requirements_gpu.txt
  setup.py
  src/transformer_deploy/backends/trt_utils.py
  src/transformer_deploy/benchmarks/utils.py
  src/transformer_deploy/convert.py
  src/transformer_deploy/utils/args.py
  tests/test_models.py
  tests/test_utils.py
Labels: enhancement

#28 add CPU inference support
  README.md
  demo/quantization_end_to_end.ipynb
  setup.cfg
  src/transformer_deploy/QDQModels/QDQRoberta.py
  src/transformer_deploy/backends/ort_utils.py
  src/transformer_deploy/backends/trt_utils.py
  src/transformer_deploy/benchmarks/utils.py
  src/transformer_deploy/convert.py
  src/transformer_deploy/templates/triton.py
  src/transformer_deploy/utils/args.py
  tests/test_models.py
  tests/test_triton.py
Labels: enhancement, performance, ONNX Runtime, Pytorch

#29 Add QAT support to more models
  README.md
  VERSION
  demo/quantization/quantization_end_to_end.ipynb
  src/transformer_deploy/QDQModels/QDQAlbert.py
  src/transformer_deploy/QDQModels/QDQBert.py
  src/transformer_deploy/QDQModels/QDQDeberta.py
  src/transformer_deploy/QDQModels/QDQDistilbert.py
  src/transformer_deploy/QDQModels/QDQElectra.py
  src/transformer_deploy/QDQModels/QDQRoberta.py
  src/transformer_deploy/QDQModels/ast_module_patch.py
  src/transformer_deploy/QDQModels/ast_operator_patch.py
  src/transformer_deploy/QDQModels/calibration_utils.py
  src/transformer_deploy/QDQModels/patch.py
  src/transformer_deploy/backends/ort_utils.py
  src/transformer_deploy/benchmarks/utils.py
  src/transformer_deploy/convert.py
  src/transformer_deploy/utils/args.py
  src/transformer_deploy/utils/python_tokenizer.py
  tests/test_ast_modifications.py
Labels: performance, quantization
