Repository ELS-RD/transformer-deploy, pull requests merged in 2022-06, with the labels that each got.

#93 fix: simplify NER pipeline on Triton server
  README.md
  src/transformer_deploy/utils/token_classifier.py
Labels: documentation, enhancement

#105 fix: add docker image version warning in README
  README.md
Labels: documentation

#103 add transformers modifications to boost performance on inference
  demo/generative-model/data/cnndm_128.txt
  demo/generative-model/data/expected_t5_output.hypo
  demo/generative-model/fastseq_test.py
  src/transformer_deploy/utils/fastseq.py
  tests/test_utils.py
Labels: performance, Pytorch
