Repository ELS-RD/transformer-deploy, pull requests merged in 2022-01, with the labels that each got.

#33 Update README.md
  README.md
Labels: bug, documentation

#32 Add website documentation
  README.md
  demo/README.md
  demo/quantization/quantization_end_to_end.ipynb
  docs/benchmarks.md
  docs/demo.md
  docs/index.md
  docs/overrides/main.html
  docs/python.md
  docs/quantization.ipynb
  docs/script/gen_doc_stubs.py
  docs/setup.md
  docs/started.md
  mkdocs.yml
  requirements_doc.txt
  src/transformer_deploy/QDQModels/QDQAlbert.py
  src/transformer_deploy/QDQModels/QDQBert.py
  src/transformer_deploy/QDQModels/QDQDeberta.py
  src/transformer_deploy/QDQModels/QDQDistilbert.py
  src/transformer_deploy/QDQModels/QDQElectra.py
  src/transformer_deploy/QDQModels/QDQRoberta.py
  src/transformer_deploy/QDQModels/ast_module_patch.py
  src/transformer_deploy/QDQModels/ast_operator_patch.py
  src/transformer_deploy/QDQModels/calibration_utils.py
  src/transformer_deploy/QDQModels/patch.py
  src/transformer_deploy/backends/ort_utils.py
  src/transformer_deploy/backends/trt_utils.py
  src/transformer_deploy/benchmarks/utils.py
  src/transformer_deploy/convert.py
  src/transformer_deploy/templates/triton.py
  src/transformer_deploy/utils/args.py
  src/transformer_deploy/utils/python_tokenizer.py
Labels: documentation

#34 Fix quantization restore function
  README.md
  src/transformer_deploy/QDQModels/QDQAlbert.py
  src/transformer_deploy/QDQModels/QDQBert.py
  src/transformer_deploy/QDQModels/QDQDeberta.py
  src/transformer_deploy/QDQModels/QDQDistilbert.py
  src/transformer_deploy/QDQModels/QDQElectra.py
  src/transformer_deploy/QDQModels/QDQRoberta.py
  src/transformer_deploy/QDQModels/ast_operator_patch.py
  src/transformer_deploy/QDQModels/ast_utils.py
  src/transformer_deploy/QDQModels/patch.py
  tests/test_ast_modifications.py
Labels: bug, quantization

#38 Improve doc
  .dockerignore
  Dockerfile
  README.md
  demo/README.md
  demo/quantization/quantization_end_to_end.ipynb
  docs/benchmarks.md
  docs/compare.md
  docs/demo.md
  docs/faq.md
  docs/index.md
  docs/onnx_convert.md
  docs/optimizations.md
  docs/python.md
  docs/quantization_ast.md
  docs/quantization_intro.md
  docs/quantization_ptq.md
  docs/quantization_theory.md
  docs/run.md
  docs/setup.md
  docs/setup_local.md
  mkdocs.yml
  resources/abbreviations.md
Labels: documentation

#42 add sentence-transformers support
  .github/workflows/python-app.yml
  README.md
  demo/quantization/quantization_end_to_end.ipynb
  demo/triton_client.py
  demo/triton_client_model.py
  demo/triton_client_tokenizer_only.py
  docs/benchmarks.md
  src/transformer_deploy/backends/ort_utils.py
  src/transformer_deploy/backends/pytorch_utils.py
  src/transformer_deploy/backends/st_utils.py
  src/transformer_deploy/convert.py
  src/transformer_deploy/templates/triton.py
  src/transformer_deploy/utils/args.py
  src/transformer_deploy/utils/python_tokenizer.py
  tests/test_models.py
  tests/test_utils.py
Labels: enhancement, Pytorch, Hugging Face
